version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: amgalan_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amgalan
    volumes: 
      - postgres_data:/var/lib/postgresql/data  
    ports: 
      - "5432:5432"

  backend: 
    build: ./backend
    container_name: amgalan_backend  
    ports: 
      - "5000:5000"
    environment:  
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: amgalan
    depends_on: 
      - postgres

  frontend:
    build: ./frontend
    container_name: amgalan_frontend
    ports:
      - "3000:80"
    depends_on: 
      - backend

volumes:
  postgres_data: